# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  build_and_test: # this can be any name you choose
    docker:
      - image: cimg/node:18.16.0
        environment:
          DATABASE_URL: postgresql://postgres@localhost/circle_test
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference

      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: postgres
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference

    working_directory: ~/IV
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Install package json dependencies
          command: npm install

      - run:
          name: Build nodejs app
          command: npm run build

      - run:
          name: Check prisma schema is valid nd push to db
          command: npm run migrate

      - run:
          command: npm run test
          name: Run tests

      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  build_test_deploy:
    jobs:
      - build_and_test
